services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    # platform: linux/arm64/v8
    container_name: go-nginx
    restart: always
    ports:
      - "80:80"  # NGINX port
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    # ports:
    #   - "6379:6379"  # Expose Redis port
    command: ["redis-server", "--appendonly", "yes"]  # Enable persistence