version: '3.7'

services:
  go_app:
    build: .
    container_name: golang-app
    # ports:
    #   - "8080:8080"  # Expose Go app on port 8080 inside the container
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"  # Expose NGINX on port 80
    depends_on:
      - go_app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
